Sprint 11
JuliDeveloper/RibbonPhotos pull request #4
Opened 2023-01-18 10:51 UTC by JuliDeveloper

2023-01-19 11:51 UTC, IBDesignable requested changes

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Helpers/UIViewController + Extension.swift
> +    }
здесь было бы удобно передать комплишен с экшеном, например, для того чтобы в случае ошибке инициировать флоу авторизации с нуля

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Helpers/URLSession + Extension.swift
> +                            print(error)
ошибку же надо вернуть, иначе не дождемся ответа

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Helpers/URLSession + Extension.swift
> +                    }
а если нет data? не пришла, но при этом статус код окей? 

формально здесь запрашивается объект и поэтому в целом ок ничего не возвращать, но с точки зрения ветвления у тебя здесь пропущен один из кейсов. Кажется, я уже обращал твое внимание на этот подход и говорила что в модуле про MovieQuiz дается стандартный подход к разбору ответа и там в ветвлении нет ошибок.

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Helpers/URLSession + Extension.swift
> +                }
ну и здесь тоже, пропущенная ветвь else

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Presentations/Auth/AuthViewController.swift
> +                    self.delegate?.didAuthenticate(vc: vc)
почему-то дальше пропихивается WebViewViewController, о котором сплеш скрин ничего не знает. По логие должен был быть передан AuthViewController

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Presentations/Auth/AuthViewController.swift
>                      self.saveAccessToken(accessToken)
по условиям задачи, когда начинаешь фетчить токен должен быть показан активити инидикатор, но его тут нет. Давай именно перед этим запросом покажем, а не в сплешскрине. Ну и соответственно разлочим экран в этом классе

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Presentations/Auth/AuthViewController.swift
> +                    self.showAlert()
Кажется, что в этом методе нужно dismiss у WebViewViewController вызвать, перед тем как фетчить (почему его нет? точно не надо добавить?)

Тогда алерт будет показан на authviewcontroller и без комплишена в алерте можно будет нажать ОК и повторить авторизацию. 

Это одно возможное решение. 

Так же здесь можно сказать сплеш. скрину, что у нас ошибка и пусть он уже решает как перезапускать состояние (идти на авторизацию или куда-то еще)

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Presentations/SplashViewController.swift
> +            fetchProfile(token: oauth2TokenStorage.bearerToken ?? "")
по тз, надо запросить данные профиля, но вот в чем беда, ты перед этим свитчуешь на главный экран. Это действие выгружает сплеш скрин из памяти, и если имя профиля еще как-то успевает синхронизироваться, то к моменту когда нужно дозапросить картинку, self уже не существует и ты теряешь запрос (строки с 64 по 70) 

Во вторую сессию пользователь остается без картинок. 

Поэтому я бы здесь написала немного иначе, начала всегда фетчить профиль, а свитч вызывала бы только когда профиль загружен и ушел запрос на аватарку 

```suggestion
        if let token = oauth2TokenStorage.bearerToken {
            fetchProfile(token: token)
```

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Presentations/SplashViewController.swift
> +                    break
break тут лишний. Я не первый раз на такое натыкаюсь, может быть это из авторского решения тянется? Буду благодарна если пришлешь скриншот/ссылку, я бы смогла передать это авторам

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Presentations/SplashViewController.swift
> +        profileService.fetchProfile(token) { result in
здесь надо начать крутить лоадер, и найти место где его отключать.

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Presentations/SplashViewController.swift
> +        }
выше оставляла комментарии, что лоадеры крутить и выключать надо рядом с запросом токена на другом экране.

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Presentations/SplashViewController.swift
> +    func didAuthenticate(vc: WebViewViewController) {
давай здесь получать AuthViewController

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Services/OAuth2Service.swift
> +                self.task = nil
если ошибка придет, то таску никто не обнулит. давай вынесем за свитч

2023-01-19 11:51 UTC, IBDesignable commented on RibbonPhotos/Services/ProfileImageService.swift
> +                print("111", "\(self.avatarURL ?? "")")
по коду расскидано много таких штук расскидано, давай договоримся что либо оставляем понятные логи (сообщение которое печатаем) либо вовсе избавляемся от всех принтов перед ревью. 

Также, тебе поможет [отладчик Xcode](https://developer.apple.com/documentation/xcode/stepping-through-code-and-inspecting-variables-to-isolate-bugs), можно ставить брейкпоинты и отсматривать состояние переменных прямо в IDE. Научиться работать с ним рано или поздно придется, предлагаю хотя бы попробовать :)

2023-01-20 13:52 UTC, JuliDeveloper commented on RibbonPhotos/Presentations/SplashViewController.swift
> +                    break
Тема: Получение базовой информации профиля -> Задача 1.б. Показать Splash Screen, пока идёт загрузка данных профиля



<img width="631" alt="Снимок экрана 2023-01-20 в 16 52 00" src="https://user-images.githubusercontent.com/44274132/213713380-873567f0-96af-43f2-9737-9645f9dca8b2.png">

2023-01-20 14:02 UTC, JuliDeveloper commented on RibbonPhotos/Presentations/SplashViewController.swift
> +    func didAuthenticate(vc: WebViewViewController) {
@JuliDeveloper в прошлом спринте пришли к выводу, что в данном случае передача AuthViewController не нужна, потому что у меня сетевой запрос обрабатывается на AuthViewController. В этом спринте чуть-чуть запуталась, поэтому напихала WebViewViewController...)

2023-01-20 14:16 UTC, JuliDeveloper commented
@IBDesignable, + я сделала новую задачу связную с версткой кода, ее добавили в тему 11 спринта в последний день 11 спринта

2023-01-20 19:56 UTC, IBDesignable approved these changes

2023-01-20 19:56 UTC, IBDesignable commented on RibbonPhotos/Presentations/Auth/AuthViewController.swift
> +                    self.showAlert(nil)
также можно UIBlockingProgressHUD.dismiss() перед switch вызвать, будет одной строчкой.

2023-01-20 19:56 UTC, IBDesignable commented on RibbonPhotos/Presentations/SplashViewController.swift
> +        self.showUserScenario()
self можно опустить

2023-01-23 10:45 UTC, merged