Sprint 12
JuliDeveloper/RibbonPhotos pull request #5
Opened 2023-01-25 18:55 UTC by JuliDeveloper

2023-01-26 09:37 UTC, ABashkirova requested changes

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Models/PhotoResult.swift
> +    }
Круто что есть конвертер!

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Presentations/ImagesList/ImagesListViewController.swift
> +            UIBlockingProgressHUD.dismiss()
не на главном потоке закрываешь

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Presentations/ImagesList/ImagesListViewController.swift
> +                    }
текст сообщения не соответсвтует действию, я бы переписала

И не понимаю зачем дисмис, можешь рассказать зачем?

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Presentations/ImagesList/SingleImageViewController.swift
> +                self.dismiss(animated: true)
какую роль здесь dismiss играет?

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Presentations/Profile/ProfileViewController.swift
> +                self.dismiss(animated: true)
опять :) 

не забывай заглядывать в документацию:
`Dismisses the view controller that was presented modally by the view controller.`

Думаю это даже работает, но по умолчанию если в комплишене действия алерта ничего не делается, он сам закрывается. Поэтому здесь это лишнее

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Presentations/SplashViewController.swift
> +                        message: "Не удалось войти в систему"
текст не совпадает с действием! запутаешь пользователя :)

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Services/ImagesListService.swift
> +        let nextPage = lastLoadedPage == nil ? 1 : lastLoadedPage ?? 0 + 1
я бы здесь добавила скобочки, иначе очень сложно читается. 
`lastLoadedPage == nil ? 1 : (lastLoadedPage ?? 0 + 1)`
Но вообще я любитель в таких случаях писать полную форму чтобы не путать читающего. В целом код пишем для людей – и то что у тебя заставляет вчитываться и вдумываться по долгу, стоит упрощать. 

```swift
let nextPage: Int 

if let lastLoadedPage {
   nextPage = lastLoadedPage + 1 
} 
else {
    nextPage = 1
}
```

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Services/ImagesListService.swift
> +                    let currentPhotos = responsePhotos.map { $0.convert() }
красиво!

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Services/ImagesListService.swift
> +
а в какой момент предполагается увеличить счетчик lastLoadedPage?

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Services/ImagesListService.swift
> +                )
а вот здесь конвертер тоже можно использовать.

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Models/PhotoResult.swift
> +            createdAt: Date().convertStringToDate(self.createdAt ?? ""),
здесь по тз должен использоваться ISO8601DateFormatter

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Helpers/Date + Extension.swift
> +    }
По ТЗ надо было подумать как реализовать инициализацию форматтеров один раз, так как эта операция достаточно дорогая. Здесь форматтер будет создан каждый раз, когда тебе понадобится модель фото преобразовать во viewModel.

В ячейке тоже создается форматтер, но там не так страшно, потому что создается он только один раз на ячейку, а их у нас всего 4 (лучше чем 20 раз и более создавать, согласишься?)

Здесь можно почитать подробнее:
https://sarunw.com/posts/how-expensive-is-dateformatter/

А подсмотреть реализацию можно в предыдущем проекте :) там статическим  свойством объект создавался

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Services/ImagesListService.swift
> +    private (set) var photos: [Photo] = []
общепринятый стиль такой 
```suggestion
    private(set) var photos: [Photo] = []
```

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Services/ImagesListService.swift
> +                self.photos.insert(newPhoto, at: index)
фото уже есть в списке, его не надо вставлять. а надо лишь обновить одно поле. 

Вставка приводит к крашу

Попробуй лайкнуть и полистать.

2023-01-26 09:37 UTC, ABashkirova commented on RibbonPhotos/Presentations/Profile/ProfileViewController.swift
> +            if action.title == "Да" {
сравнивать по строке не очень хорошо, если тебе приходится так сравнивать, с высокой вероятностью код получится не стабильным, так как можно опечататься, и не расширяемым, так как приложение может быть локализовано на несколько языков. 

Обычно просто передают два (N) разных комплишенов на каждую кнопку. Похожим образом работает и API алерта, там каждый экшен надо написать отдельно.

2023-01-26 09:37 UTC, ABashkirova commented
Краш:
<img width="1792" alt="Снимок экрана 2023-01-26 в 11 37 21" src="https://user-images.githubusercontent.com/20269264/214803521-5fed4c2d-4bc5-483e-8ce1-647966aa1e56.png">

2023-01-26 09:48 UTC, ABashkirova commented on RibbonPhotos/Services/ImagesListService.swift
> +                )
а лучше просто изменить свойство isLiked, а не создавать новый элемент

2023-01-30 15:23 UTC, JuliDeveloper commented
@ABashkirova, + сделала задание связанное с анимацией

2023-01-30 15:25 UTC, JuliDeveloper commented on RibbonPhotos/Presentations/ImagesList/ImagesListViewController.swift
> +                    }
@ABashkirova, знаю что он по умолчанию сам закрывается, но я была в отчаянии, action у alert не срабатывал, а ошибка в коде оказалась совсем в другом, а эти dismiss() забыла убрать...

2023-01-30 15:57 UTC, ABashkirova commented on RibbonPhotos/Presentations/ImagesList/ImagesListViewController.swift
> +                    }
молодец что разобралась! 

Если что-то не получается, не забывай отходить от кода отдыхать, коду иногда надо настояться :)

2023-01-31 15:45 UTC, ABashkirova approved these changes

2023-01-31 15:45 UTC, ABashkirova commented on RibbonPhotos/Helpers/Gradient + Extension.swift
> +
👍🏻

2023-01-31 15:45 UTC, ABashkirova commented on RibbonPhotos/Presentations/Profile/ProfileViewController.swift
> +        let imageGradient = CAGradientLayer().createLoadingGradient(70, 70, 35)
без именованных аргументов такое сложно читать :( что за магия чисел, не разгадать – придется смотреть сам метод. Чтобы время на это не тратить, лучше для читаемости как раз именованные аргументы

2023-01-31 15:45 UTC, ABashkirova commented on RibbonPhotos/Services/ImagesListService.swift
> +                    self.lastLoadedPage = (self.lastLoadedPage ?? 0) + 1
self.lastLoadedPage = nextPage

2023-01-31 15:45 UTC, ABashkirova commented on RibbonPhotos/Helpers/Date + Extension.swift
> +        let dateFormatter =  ISO8601DateFormatter()
все еще будет форматтер создаваться на каждый запрос. тут надо доправить.

2023-01-31 15:45 UTC, ABashkirova commented on RibbonPhotos/Helpers/Date + Extension.swift
> +private let dateFormatter: DateFormatter = {
можно приватным статическим свойством внутри экстеншена

2023-02-01 12:36 UTC, JuliDeveloper commented on RibbonPhotos/Helpers/Date + Extension.swift
> +private let dateFormatter: DateFormatter = {
@ABashkirova, спасибо за такой подробный разбор! Хорошей недели:)

2023-02-01 12:39 UTC, merged