Sprint 13
JuliDeveloper/RibbonPhotos pull request #6
Opened 2023-02-16 21:10 UTC by JuliDeveloper

2023-02-18 06:57 UTC, mmbabaev requested changes

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Helpers/AuthConfiguration.swift
> +    init(
Кажется, что можно не писать свой ринит здесь, для структур такой стандартный init автосгенерирован

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/Auth/AuthHelper.swift
> +        guard var urlComponents = URLComponents(string: authConfiguration.unsplashAuthorizeURLString) else { return URL(fileURLWithPath: "") }
`URL(fileURLWithPath: "")` - с одной стороны интересный способ избавиться от опционала в возвращаемом значении. С другой стороны это ошибочная ситуация, которую будет сложнее выявить, чем если бы опционал был.

Предлагаю такие варианты: 

1) вставить `assertionFailure()` c сообщением при возврате такого урла. Так во время разработки будет легче поймать этот баг 
2) Или не использовать такой способ и возвращать nil 
3) Оба варианта вместе, вернуть nil и бросать assertionFailure

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/Auth/AuthHelper.swift
> +            return nil
проводя аналогию с authURL: функция `code(from` была бы чуть хуже, если бы мы возвращали пустую строку вместо nil

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/Auth/WebViewPresenter.swift
> +    private var helper: AuthHelperProtocol
кажется, что тут можно использовать let вместо var

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/ImagesList/ImageListViewPresenter.swift
> +    var view: ImagesListViewControllerProtocol? { get set }
в протоколах можно не добавлять зависимости (view в протоколе presenter, presenter в протоколе view)

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/Profile/ProfileViewPresenter.swift
> +        profileService = ProfileService.shared
будет лучше передавать зависимости в init, пусть даже с дефектными аргументами. Так мы делаем класс тестируемым (сможем потом подменить зависимости)
```
init(
  viewController: ProfileViewControllerProtocol,
  profileService: ProfileService = .shared, 
...
)
````

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotosTests/ImageListViewTest.swift
> +final class ImageListViewTest: XCTestCase {
вы во всех тестах этого класса проверяете не реальный код, а мок, написанный выше. 

- GIVEN: Настроить начальное состояние.
один класс теста должен проверять поведение одного класса (у вас это ViewController), его зависимости должны быть подменены моками (вы подменили presenterSpy) - тут ок 
- WHEN: Вызвать функцию тестируемого класса. 
дальше мы хотим проверить какую-то функцию тестируемого класса. Мы не должны вызывать функции презентера напрямую. Мы хотим вызвать функцию ViewController и проверить, что это привело к вызову функции в presenter
- THEN проверяем конечное состояние после вызова функции, что должно произойти. 


У вас проблема со вторым пунктом. Нужно вызвать функцию у VIewController, не у Мока презентера напрямую

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotosTests/ProfileViewTest.swift
> +final class ProfileViewPresenterSpy: ProfileViewPresenterProtocol {
аналогично

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotosTests/WebViewTests.swift
> +final class WebViewTests: XCTestCase {
здесь все окей. Обратите внимание, в каждой функции вы вызываете функцию одного объекта (тестируемого) и проверяете, что это приводит к каким-то эффектам в spy объекте

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/ImagesList/ImagesListViewController.swift
> +    var presenter: ImageListViewPresenterProtocol?
можно сделать через lazy: 
```swift
lazy var presenter: ImageListPresenterProtocol = {
      ImageListViewPresenter(viewController: self)
}()
```

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/ImagesList/ImageListViewPresenter.swift
> +    func sendArrayPhotos() -> [Photo] {
Функция называется "Отправить array photos " , но она отдает фотографии из сервиса. Лучше назвать `getPhotos`, `getPhotosArray` или сделать вычисляемое свойство 

```swift
var photos: [Photo] {
  imageListService?.photos ?? []
}
```

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/ImagesList/ImageListViewPresenter.swift
> +    private let imageListService: ImagesListService?
здесь не нужен опционал, вы проставляете сервис в init

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/Profile/ProfileViewPresenter.swift
> +        WebViewViewController.clean()
так делать нехорошо, потому что это не тестируемо. 
Давайте вынесем статическую функцию в отдельный сервис и передадим в presenter. После этого можно будет замокать этот сервис в тестах и проверить, что функция clean вызывается

2023-02-18 06:57 UTC, mmbabaev commented on RibbonPhotos/Presentations/Profile/ProfileViewPresenter.swift
> +        WebViewViewController.clean()
Также нехорошо, что ProfilePresenter (бизнес логика Profile) знает что-то 
1) о другом модуле WebView
2) о конкретной реализации WebViewController

2023-02-18 14:47 UTC, JuliDeveloper commented on RibbonPhotos/Helpers/AuthConfiguration.swift
> +    init(
Знаю что у структур есть встроенный инициализатор, но делала как в учебнике:(

2023-02-18 15:50 UTC, JuliDeveloper commented on RibbonPhotosTests/ImageListViewTest.swift
> +final class ImageListViewTest: XCTestCase {
@mmbabaev, правильно ли я понимаю, что протестировать методы presenter-ов, которые срабатывают при взаимодействии с UI, в unit-тестах нельзя?
Я удалила два теста, тест отвечающий за выход из аккаунт и тест изменяющий лайки.

2023-02-18 15:56 UTC, JuliDeveloper commented on RibbonPhotos/Presentations/ImagesList/ImageListViewPresenter.swift
> +    var view: ImagesListViewControllerProtocol? { get set }
@mmbabaev, получается, что у меня протоколы для viewController-ов пустые, но и удалить я так понимаю их не могу, потому что использую их для свойств view в presenter, верно? Или как-то иначе можно?

2023-02-19 07:27 UTC, mmbabaev approved these changes

2023-02-19 07:27 UTC, mmbabaev commented on RibbonPhotos/Presentations/ImagesList/ImageListViewPresenter.swift
> +    var view: ImagesListViewControllerProtocol? { get set }
не понял почему пустые, там же останутся функции,  которые вызывает presenter?

2023-02-19 07:27 UTC, mmbabaev commented on RibbonPhotosTests/ImageListViewTest.swift
> +final class ImageListViewTest: XCTestCase {
Тут лучше будет протестировать методы презентера. Например, протестировать, что 
если вызван logout(), то `oAuth2TokenStorage.bearerToken == nil` и `helper.cleanCookies` была вызвана.

По моему опыту ViewController обычно не покрывают юнит тестами, там либо UI, который лучше проверять Snapshot тестами, либо это вызовы функций презентера. А уже методы презентера имеет тестировать, потому что там бизнес логика, использование сервисов.

2023-02-19 07:27 UTC, mmbabaev commented on RibbonPhotosUITests/RibbonPhotosUITests.swift
> +final class RibbonPhotosUITests: XCTestCase {
Тесты не проходят, но я не заметил это в прошлую проверку, поэтому не буду считать за критическое замечание. Просто почините, пожалуйста


<img width="844" alt="Screenshot 2023-02-19 at 10 26 22" src="https://user-images.githubusercontent.com/12600807/219934815-6adb857e-ff73-4a0e-a888-289b9c678b10.png">
<img width="802" alt="Screenshot 2023-02-19 at 10 26 11" src="https://user-images.githubusercontent.com/12600807/219934808-d43650d5-5a4d-4d3b-88ed-2c228331b7bf.png">

2023-02-24 12:32 UTC, merged